server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb:http://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**



management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO # Set the default logging level to INFO
    org.springframework.cloud.gateway: DEBUG # Enable detailed logging for Spring Cloud Gateway
    org.springframework.web: DEBUG # Enable detailed logging for Spring Web, which includes gateway filters and routes
    org.springframework.cloud.netflix.eureka: DEBUG # Enable detailed logging for Eureka client
    org.springframework.http.server.reactive: DEBUG # Enable detailed logging for HTTP server handling reactive requests