spring:
  application:
  name: SpringGraphQl

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 1000

sentry:
  dsn: ${SENTRY_DSN}
  tracesSampleRate: 1.0
  exception-resolver-order: -2147483647

