spring:
  application:
    name: department-service

  datasource:
    url: jdbc:postgresql://localhost:5432/department
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: "optional:configserver:http://localhost:8088"